=== City-of-Helsinki/ya-integration/src/main/resources/schema/kipa/json_schema_PT_PT55_TOJT.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "delivery": {
        "type": "object",
        "properties": {
          "fileName": {
            "type": "string"
          },
          "id": {
            "type": "integer",
            "minimum": 0
          },
          "sentAt": {
            "type": "string",
            "format": "date"
          },
          "from": {
            "type": "string",
            "maxLength": 2
          },
          "to": {
            "type": "string"
          }
        },
        "required": ["fileName", "id", "sentAt", "from", "to" ]
      },
      "bizTalkPipe": {
        "type": "string"
      },
      "invoiceNumber": {
        "type": "integer",
        "minimum": 0
      },
      "invoiceDate": {
        "type": "string",
        "format": "date"
      },
      "dueDate": {
        "type": "string",
        "format": "date"
      },
      "receiptDate": {
        "type": "string",
        "format": "date"
      },
      "grossSum": {
        "type": "number",
        "minimum": 0
      },
      "currency": {
        "type": "string",
        "maxLength": 3
      },
      "ourReference": {
        "type": "string"
      },
      "customerBankReference": {
        "type": ["string", "null"]
      },
      "periodStartDate": {
        "type": ["string", "null"],
        "format": "date"
      },
      "periodEndDate": {
        "type": ["string", "null"],
        "format": "date"
      },
      "paymentPeriodStartDate": {
        "type": ["string", "null"],
        "format": "date"
      },
      "paymentPeriodEndDate": {
        "type": ["string", "null"],
        "format": "date"
      },
      "employeeName": {
        "type": ["string", "null"]
      },
      "customProjectCode": {
        "type": ["string", "null"]
      },
      "receiver": {
        "type": "object",
        "properties": {
          "profitCenterCode": {
            "type": ["integer", "null"]
          },
          "bankAccount": {
            "type": "object",
            "properties": {
              "value": {
                "type": "string",
                "maxLength": 34
              },
              "bicCode": {
                "type": "string",
                "maxLength": 11
              }
            },
            "required": ["value", "bicCode"]
          },
          "name": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string"
              },
              "lastName": {
                "type": "string"
              }
            },
            "required": ["firstName", "lastName"]
          },
          "socialSecurityNumber": {
            "type": ["string", "null"],
            "maxLength": 11
          },
          "businessId": {
            "type": "string",
            "maxLength": 9
          },
          "postalAddress": {
            "type": "object",
            "properties": {
              "addressLine": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "postalCode": {
                "type": "string",
                "maxLength": 5
              },
              "postOffice": {
                "type": "string"
              },
              "country": {
                "type": "string",
                "maxLength": 2
              }
            },
            "required": ["addressLine", "postalCode", "postOffice", "country"]
          },
          "number": {
            "type": ["integer", "null"]
          }
        },
        "required": ["profitCenterCode", "bankAccount", "name", "businessId", "postalAddress"]
      },
      "posting": {
        "type": "object",
        "properties": {
          "postingInstallment": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "sum": {
                  "type": "number",
                  "minimum": 0
                },
                "businessBookkeepingAccount": {
                  "type": ["integer", "null"]
                },
                "financeAssessmentAccount": {
                  "type": ["integer", "null"]
                },
                "followUpCode1": {
                  "type": ["integer", "null"]
                },
                "followUpCode2": {
                  "type": ["integer", "null"]
                },
                "partnerCode": {
                  "type": ["string", "null"]
                },
                "functionCode": {
                  "type": ["string", "null"]
                },
                "ovt": {
                  "type": ["string", "null"]
                },
                "operationUnit": {
                  "type": ["integer", "null"]
                },
                "projectCode": {
                  "type": ["string", "null"]
                },
                "municipalityCode": {
                  "type": "string",
                  "maxLength": 3
                },
                "vatCode": {
                  "type": "string",
                  "maxLength": 4
                }
              },
              "required": ["sum", "municipalityCode", "vatCode"]
            }
          },
          "accountsLedgerReceiptType": {
            "type": "string",
            "maxLength": 2
          }
        },
        "required": ["accountsLedgerReceiptType"]
      },
      "view": {
        "type": "object",
        "properties": {
          "type": {
            "type": ["string", "null"]
          },
          "roadName": {
            "type": ["string", "null"]
          },
          "roadId": {
            "type": ["string", "null"]
          },
          "usePriviledgeUnitId": {
            "type": ["string", "null"]
          },
          "municipality": {
            "type": "object",
            "properties": {
              "value": {
                "type": ["string", "null"]
              },
              "code": {
                "type": ["string", "null"],
                "maxLength": 3
              }
            }
          },
          "paymentDecisionRecordNumber": {
            "type": "string"
          },
          "paymentDecisionDate": {
            "type": "string",
            "format": "date"
          },
          "grantDecisionRecordNumber": {
            "type": "string"
          },
          "businessUnit": {
            "type": "object",
            "properties": {
              "value": {
                "type": "string"
              },
              "code": {
                "type": "integer",
                "minimum": 0
              }
            },
            "required": ["value", "code"]
          },
          "creator": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  }
                },
                "required": ["firstName", "lastName"]
              }
            },
            "required": ["name"]
          },
          "paymentSubjectInspector": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  }
                },
                "required": ["firstName", "lastName"]
              },
              "email": {
                "type": "object",
                "properties": {
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["value"]
              }
            },
            "required": ["name", "email"]
          },
          "verifyDate": {
            "type": "string",
            "format": "date"
          },
          "paymentPresenter": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  }
                },
                "required": ["firstName", "lastName"]
              },
              "email": {
                "type": "object",
                "properties": {
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["value"]
              },
              "signedTime": {
                "type": "string",
                "format": "date"
              }
            },
            "required": ["name", "email", "signedTime"]
          },
          "paymentAcceptor": {
            "type": "object",
            "properties": {
              "name": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  }
                },
                "required": ["firstName", "lastName"]
              },
              "email": {
                "type": "object",
                "properties": {
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["value"]
              },
              "signedTime": {
                "type": "string",
                "format": "date"
              }
            },
            "required": ["name", "email", "signedTime"]
          },
          "additionalInformation": {
            "type": "string"
          },
          "rows": {
            "type": "object",
            "properties": {
              "row": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "grossSum": {
                      "type": "number",
                      "minimum": 0
                    },
                    "vatPercentage": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 100
                    },
                    "vatSum": {
                      "type": "number",
                      "minimum": 0
                    },
                    "netSum": {
                      "type": "number",
                      "minimum": 0
                    }
                  },
                  "required": ["description", "grossSum", "vatPercentage", "vatSum", "netSum"]
                }
              }
            },
            "required": ["row"]
          },
          "vatSum": {
            "type": "number",
            "minimum": 0
          },
          "netSum": {
            "type": "number",
            "minimum": 0
          },
          "aidType": {
            "type": "string"
          },
          "language": {
            "type": "integer"
          }
        },
        "required": [
          "paymentDecisionRecordNumber", 
          "paymentDecisionDate", 
          "grantDecisionRecordNumber", 
          "verifyDate", 
          "businessUnit", 
          "additionalInformation",
          "vatSum",
          "netSum",
          "aidType",
          "language"
        ]
      },
      "version": {
        "type": "string"
      },
      "claimType": {
        "type": "string"
      },
      "auraAccount": {
        "type": "string"
      },
      "sectorIdentifier": {
        "type": "string"
      },
      "participantHomeMunicipality": {
        "type": "string",
        "maxLength": 3
      },
      "recipientMunicipality": {
        "type": "string",
        "maxLength": 3
      },
      "employmentMunicipality": {
        "type": ["string", "null"],
        "maxLength": 3
      },
      "payerBusinessId": {
        "type": ["string", "null"],
        "maxLength": 9
      },
      "acculturingStatus": {
        "type": ["boolean", "null"]
      },
      "originalInvoiceNumber": {
        "type": ["string", "null"]
      },
      "originalBuyerReferenceIdentifier": {
        "type": ["string", "null"]
      }
    },
    "required": [
      "bizTalkPipe",
      "invoiceNumber",
      "invoiceDate",
      "dueDate",
      "receiptDate",
      "grossSum",
      "currency",
      "ourReference",
      "receiver",
      "posting",
      "view",
      "version",
      "claimType",
      "auraAccount",
      "sectorIdentifier",
      "participantHomeMunicipality",
      "recipientMunicipality"
    ]
  }

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/kirjanpito_data_tojt.json
{"delivery":{"fileName":"YA_p24_091_20241031100100_0_TOJT.json","id":60025917,"sentAt":"2024-10-31 10:01:00","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025917,"invoiceDate":"2024-10-31 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-31 00:00:00","grossSum":1255.0,"currency":"EUR","ourReference":"Hakemus työolosuhteiden järjestelytuesta TOJT/24170/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-10-31 00:00:00","periodEndDate":"2024-12-31 00:00:00","paymentPeriodStartDate":"2024-10-01 00:00:00","paymentPeriodEndDate":"2024-10-31 00:00:00","employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI3952900240167500","bicCode":"OKOYFIHH"},"name":{"firstName":"Testifirma OY","lastName":""},"socialSecurityNumber":null,"businessId":"8262500-3","postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":1255.0,"businessBookkeepingAccount":82310000,"financeAssessmentAccount":42332305109,"followUpCode1":38025110,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0056","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Työolosuhteiden järjestelytuki","roadName":"5086YA0056","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"TOJT/24170/2024","paymentDecisionDate":"2024-10-31 00:00:00","grantDecisionRecordNumber":"TOJT/24170/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Emilia","lastName":"Kujala"}},"paymentSubjectInspector":{"name":{"firstName":"Emilia","lastName":"Kujala"},"email":{"value":"emilia.kujala@ely-keskus.fi"}},"verifyDate":"2024-10-31 09:59:26","paymentPresenter":{"name":{"firstName":"Emilia","lastName":"Kujala"},"email":{"value":"emilia.kujala@ely-keskus.fi"},"phoneNumber":"-","signedTime":"2024-10-31 09:59:15"},"paymentAcceptor":{"name":{"firstName":"Mari","lastName":"Voutilainen"},"email":{"value":"mari.voutilainen@ely-keskus.fi"},"phoneNumber":null,"signedTime":"2024-10-31 10:00:06"},"additionalInformation":"Työolosuhteiden järjestelytukihakemuksen tuki: 5086YA0056. Myöntöpäätös: 31.10.2024. 5555. Kustannuksia haettu 01.10.2024 - 31.10.2024.","rows":{"row":[{"description":"Työolosuhteiden järjestelytuki","grossSum":1255.0,"vatPercentage":0,"vatSum":0,"netSum":1255.0}]},"vatSum":0,"netSum":1255.0,"aidType":"99","language":1},"version":"2.3","claimType":"TYOOLOSUHTEIDEN_JARJESTELYTUKI","auraAccount":"4300","sectorIdentifier":"S.11","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/kirjanpito_data_pt.json
{"delivery":{"fileName":"YA_p24_091_20241031115100_0_PT.json","id":60025925,"sentAt":"2024-10-31 11:51:00","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025925,"invoiceDate":"2024-10-31 00:00:00","dueDate":"2024-11-02 00:00:00","receiptDate":"2024-10-31 00:00:00","grossSum":1250.0,"currency":"EUR","ourReference":"Palkkatuki PT/24172/2024","customerBankReference":"12 34561","periodStartDate":"2024-07-01 00:00:00","periodEndDate":"2024-10-31 00:00:00","paymentPeriodStartDate":"2024-09-01 00:00:00","paymentPeriodEndDate":"2024-09-30 00:00:00","employeeName":"Seppo Sepomäkinen","customProjectCode":"12345","receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI3952900240167500","bicCode":"OKOYFIHH"},"name":{"firstName":"Helsingin kuppi","lastName":""},"socialSecurityNumber":"210218-265B","businessId":"6631305-0","postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90055},"posting":{"postingInstallment":[{"sum":1250.0,"businessBookkeepingAccount":82310000,"financeAssessmentAccount":202402024,"followUpCode1":null,"followUpCode2":38099272,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":1,"projectCode":"5086YA0058","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Palkkatukihakemuksen tuki","roadName":"5086YA0058","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"PT/24172/2024","paymentDecisionDate":"2024-10-31 00:00:00","grantDecisionRecordNumber":"PT/24172/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Emma","lastName":"Virtanen"}},"paymentSubjectInspector":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"}},"verifyDate":"2024-10-31 11:50:40","paymentPresenter":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"},"phoneNumber":"-","signedTime":"2024-10-31 11:47:10"},"paymentAcceptor":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"},"phoneNumber":null,"signedTime":"2024-10-31 11:50:47"},"additionalInformation":"Palkkatukihakemuksen tuki: 5086YA0058. Myöntöpäätös: 31.10.2024. 202402024/2024. Kustannuksia haettu 01.09.2024 - 30.09.2024.","rows":{"row":[{"description":"Palkkatukihakemuksen tuki erä 3-2024","grossSum":1250.0,"vatPercentage":0,"vatSum":0,"netSum":1250.0}]},"vatSum":0,"netSum":1250.0,"aidType":"6T","language":1},"version":"2.3","claimType":"PALKKATUKI","auraAccount":"4746","sectorIdentifier":"S.11","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}
